// The website's pictures, drawn by the app that the website is about.
//
// Maze Hippo has no site of its own: hippoherd.com/mazehippo IS its site, and
// `website/` in this repository is where that page is written. Its pictures
// have to come from somewhere, and the choice is between a screenshot somebody
// took once on a phone they happened to have, and this — the real painter, the
// real camera, the real generator, rasterised at a size the web wants.
//
// This is the same call the rest of `tool/` makes and for the same reason.
// `boop.dart` is the sound's source of record and `app_icon.dart` is the icon's;
// this is the source of record for every picture on the page. A capture of a
// running app goes stale silently — the palette changes, the head gets longer,
// and the page keeps showing last month's game. These are regenerated by
// `make site-images` and the diff says what moved.
//
// Run via `flutter test` rather than `dart run`, like `tool/board.dart`, because
// rasterising needs `dart:ui` and `dart:ui` needs the engine up.
//
// Writes into the project rather than into /tmp: the files it makes are what
// ships to hippoherd, so they are tracked, and the tool is how they are redrawn.
//
// ignore_for_file: avoid_print

import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mazehippo/puzzle/puzzle.dart';
import 'package:mazehippo/render/board_painter.dart';
import 'package:mazehippo/render/camera.dart';

/// Where the pictures land.
///
/// The Makefile passes an absolute path, because a `flutter test` runs with its
/// working directory at the package root — `src/` — and the website is a level
/// above that. The default is the same place spelled relatively, so that running
/// this file straight out of an editor still works.
final String out =
    Platform.environment['WEBSITE_OUT'] ??
    '${Directory.current.path}/../website';

/// One board, portrait, at twice the phone's width.
///
/// Deliberately NOT the phone's shape. `tool/board.dart` renders 390 × 700,
/// which is the game screen's board area, and on a phone the space above and
/// below a fitted board is where the lives, the clock and the back button live.
/// This tool draws the board and nothing else, so at 700 tall those bands come
/// out as two fingers of empty dark that on the page read as a picture with
/// something missing rather than as a screen with chrome cropped off.
///
/// 780 × 1000 keeps the width — and therefore `fit()`, which scales on the
/// shorter side, and therefore the board pixel for pixel — and takes back most
/// of the emptiness. What the page then shows is a board, which is what the
/// captions call it. A screenshot of the whole screen would have to come from a
/// phone, and would go stale the first time the chrome moved.
const Size shot = Size(780, 1000);

/// The dark the board is drawn on, reused for the ground of the composites so
/// the cards sit on their own colour rather than on a second, nearly-identical
/// one that would show as a seam.
const Color ground = BoardPainter.background;

Future<ui.Image> render(Size size, void Function(Canvas) draw) async {
  final ui.PictureRecorder recorder = ui.PictureRecorder();
  draw(Canvas(recorder));
  return recorder.endRecording().toImage(
    size.width.round(),
    size.height.round(),
  );
}

Future<void> save(String name, ui.Image image) async {
  final ByteData bytes = (await image.toByteData(
    format: ui.ImageByteFormat.png,
  ))!;
  final File file = File('$out/$name');
  await file.parent.create(recursive: true);
  await file.writeAsBytes(bytes.buffer.asUint8List());
  print('wrote ${file.path}  ${image.width} × ${image.height}');
}

/// A level, fitted to [shot], with whatever frames the caller wants on it.
///
/// [frames] defaults to every arrow standing still, which is what a board looks
/// like before anyone has touched it.
Future<ui.Image> boardOf(
  int number, {
  List<ArrowFrame> Function(Level level)? frames,
}) async {
  final Level level = generateLevel(number);
  final BoardCamera camera = BoardCamera(size: level.size, viewport: shot)
    ..fit();
  final List<ArrowFrame> painted =
      frames?.call(level) ??
      <ArrowFrame>[for (final Arrow arrow in level.arrows) ArrowFrame(arrow)];
  return render(
    shot,
    (Canvas canvas) =>
        BoardPainter(camera: camera, frames: painted).paint(canvas, shot),
  );
}

/// Three boards, side by side, as one landscape picture.
///
/// The hero slot on the page and the Open Graph card are both landscape, and a
/// single portrait board dropped into either one is mostly empty space with a
/// tall sliver of game in the middle. Three of them at three difficulties is
/// also the more honest picture: the thing that changes across the campaign is
/// the tangle, and one board cannot show that.
///
/// Geometry is proportional to [width] so that the hero and the OG card are the
/// same drawing at two sizes rather than two drawings that have to be kept in
/// step. The centre card is larger and higher than its neighbours — depth, and
/// it puts the middle difficulty where the eye lands first.
Future<ui.Image> composite(
  double width,
  double height,
  List<ui.Image> boards,
) async {
  assert(boards.length == 3, 'the composite is three cards wide');

  // As a fraction of the frame. Card height first; the width follows from the
  // board's own aspect ratio, so a card is never distorted.
  const double centreHeight = 0.88;
  const double sideHeight = 0.72;
  const double gap = 0.02;

  final double aspect = shot.width / shot.height;
  final double ch = height * centreHeight;
  final double cw = ch * aspect;
  final double sh = height * sideHeight;
  final double sw = sh * aspect;
  final double g = width * gap;

  final double centreX = (width - cw) / 2;
  final Rect centre = Rect.fromLTWH(centreX, (height - ch) / 2, cw, ch);
  final Rect left = Rect.fromLTWH(centreX - g - sw, (height - sh) / 2, sw, sh);
  final Rect right = Rect.fromLTWH(centre.right + g, (height - sh) / 2, sw, sh);

  return render(Size(width, height), (Canvas canvas) {
    canvas.drawRect(
      Rect.fromLTWH(0, 0, width, height),
      Paint()..color = ground,
    );

    // Back to front, so the centre card's shadow falls on its neighbours rather
    // than the other way round.
    for (final (Rect at, ui.Image image) in <(Rect, ui.Image)>[
      (left, boards[0]),
      (right, boards[2]),
      (centre, boards[1]),
    ]) {
      final RRect card = RRect.fromRectAndRadius(
        at,
        Radius.circular(at.width * 0.055),
      );

      // The cards are the same dark as the ground they sit on, so without a
      // shadow under them and a hairline around them they do not read as
      // separate objects at all — the three boards merge into one field of
      // arrows. Both are doing the same job from opposite sides.
      canvas.drawRRect(
        card.shift(Offset(0, at.height * 0.03)),
        Paint()
          ..color = const Color(0xCC000000)
          ..maskFilter = MaskFilter.blur(BlurStyle.normal, at.width * 0.05),
      );

      canvas.save();
      canvas.clipRRect(card);
      canvas.drawImageRect(
        image,
        Rect.fromLTWH(0, 0, image.width.toDouble(), image.height.toDouble()),
        at,
        Paint()..filterQuality = FilterQuality.high,
      );
      canvas.restore();

      canvas.drawRRect(
        card,
        Paint()
          ..style = PaintingStyle.stroke
          ..strokeWidth = at.width * 0.004
          ..color = const Color(0x26FFFFFF),
      );
    }
  });
}

void main() {
  // The gallery: four boards across the campaign, then the two frames that show
  // what a tap does. Numbered because the page reads them in order and the
  // order is the argument — it gets bigger, then it gets denser, then here is
  // what happens when you are right and when you are wrong.
  test('the gallery', () async {
    await save('images/screens/01-level-001.png', await boardOf(1));
    await save('images/screens/02-level-012.png', await boardOf(12));
    await save('images/screens/03-level-030.png', await boardOf(30));
    await save('images/screens/04-level-100.png', await boardOf(100));
  });

  test('an arrow on its way out', () async {
    // Caught straddling the edge, which is the only moment that reads as
    // leaving in a still picture. Anywhere earlier and the arrow is just an
    // arrow standing somewhere slightly different from where it started —
    // there is no "before" beside it on the page to compare against, so the
    // motion has to be legible from this frame alone. Half of it outside the
    // lattice is unambiguous.
    //
    // `Arrow.pathDot` is defined past the edge on purpose (leaving is the arrow
    // walking off the end of its own path), and nothing clips the painter to
    // the board, so the part that has gone is really drawn out there in the
    // margin rather than being cut off at the last dot.
    //
    // Deliberately a bent arrow, and the longest one available: a straight one
    // sliding out could be a rigid translation, and the whole of how this game
    // moves is that it is not. The body threading around its own corner is the
    // one thing a still can say about the movement.
    await save(
      'images/screens/05-leaving.png',
      await boardOf(
        1,
        frames: (Level level) {
          final Board board = level.board();
          final List<Arrow> bent = <Arrow>[
            for (final Arrow arrow in board.freeArrows)
              if (arrow.corners.length > 2) arrow,
          ]..sort((Arrow a, Arrow b) => b.dots.length - a.dots.length);
          final Arrow leaving = bent.isEmpty
              ? board.freeArrows.first
              : bent.first;

          // Half the body past the edge. `exitSteps` is the whole journey —
          // the lane plus the arrow's own length — so backing off by half a
          // length lands the midpoint of the arrow exactly on the boundary.
          final double halfway =
              board.exitSteps(leaving) - leaving.dots.length / 2;

          return <ArrowFrame>[
            for (final Arrow other in level.arrows)
              if (!identical(other, leaving)) ArrowFrame(other),
            ArrowFrame(leaving, steps: halfway),
          ];
        },
      ),
    );
  });

  test('a tap that was wrong', () async {
    // The frame a player is looking at one second after losing a life: the
    // arrow stopped where it ran out of room, and the arrow that stopped it lit
    // up behind. It is on the page because it is the only rule the game has,
    // and a picture of it says more than the sentence next to it does.
    await save(
      'images/screens/06-blocked.png',
      await boardOf(
        12,
        frames: (Level level) {
          final Board board = level.board();
          for (final Arrow arrow in level.arrows) {
            final Slide slide = board.slide(arrow);
            if (slide.escapes) {
              continue;
            }
            return <ArrowFrame>[
              for (final Arrow other in level.arrows)
                if (!identical(other, arrow) &&
                    !identical(other, slide.blocker))
                  ArrowFrame(other),
              ArrowFrame(slide.blocker!, mood: ArrowMood.culprit),
              ArrowFrame(
                arrow,
                steps: slide.steps.toDouble(),
                mood: ArrowMood.blocked,
              ),
            ];
          }
          // Unreachable on a generated level — every one of them has a blocked
          // arrow, or there would be no puzzle — but a `for` that falls out has
          // to return something, and an empty board is a picture that is
          // obviously wrong rather than one that is subtly wrong.
          return <ArrowFrame>[];
        },
      ),
    );
  });

  test('the hero and the card', () async {
    // One easy board, one from the middle, one from the end.
    final List<ui.Image> three = <ui.Image>[
      await boardOf(1),
      await boardOf(30),
      await boardOf(100),
    ];

    // 2400 × 1200 for the hero, which is 2:1 and lands on the page at about
    // 570 CSS pixels wide — so this is a 4× raster and stays sharp on anything.
    await save('images/hero.png', await composite(2400, 1200, three));

    // 1200 × 630 is what Open Graph and Twitter both want, and it is not 2:1 —
    // it is 1.905:1, near enough that the same proportional layout fills it
    // without a special case.
    await save('images/og.png', await composite(1200, 630, three));
  });
}
