import 'dart:async';

import 'package:flutter/material.dart';

import '../audio/ambience.dart';
import '../audio/audio_settings.dart';
import '../puzzle/puzzle.dart';
import '../render/board_painter.dart';
import '../render/camera.dart';
import 'chrome.dart';
import 'game_screen.dart';
import 'level_picker.dart';
import 'store.dart';

/// The front page.
class TitleScreen extends StatefulWidget {
  const TitleScreen({super.key});

  @override
  State<TitleScreen> createState() => _TitleScreenState();
}

class _TitleScreenState extends State<TitleScreen> {
  /// A real board, dimmed, behind the title.
  ///
  /// Level 8 rather than a drawing of one: it is generated by the same code the
  /// game runs and looks like what the player is about to be given, and it
  /// costs nothing to be honest about it. Held in state so it does not change
  /// on every rebuild — a title screen whose backdrop reshuffles when a button
  /// is pressed reads as a glitch.
  late final Level _backdrop = generateLevel(8);

  Future<void> _open(Widget screen) async {
    await Navigator.of(
      context,
    ).push(MaterialPageRoute<void>(builder: (BuildContext _) => screen));
    // Progress may have moved while that screen was up, and the counter below
    // is showing it.
    if (mounted) {
      setState(() {});
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: BoardPainter.background,
      body: Stack(
        fit: StackFit.expand,
        children: <Widget>[
          _Backdrop(level: _backdrop),
          SafeArea(
            child: Column(
              children: <Widget>[
                const Spacer(flex: 3),
                const Text(
                  'Maze Hippo',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 40,
                    fontWeight: FontWeight.w800,
                    letterSpacing: -0.5,
                  ),
                ),
                const SizedBox(height: 6),
                const Text(
                  'tap an arrow. mind what is in the way.',
                  style: TextStyle(color: Colors.white38, fontSize: 14),
                ),
                const Spacer(flex: 2),
                MenuButton(
                  label: progress.clearedCount == 0
                      ? 'Play'
                      : 'Continue — level ${progress.next}',
                  icon: Icons.play_arrow_rounded,
                  tint: gradeColour(LevelPlan.gradeOf(progress.next)),
                  onPressed: () =>
                      unawaited(_open(GameScreen(startAt: progress.next))),
                ),
                const SizedBox(height: 12),
                MenuButton(
                  label: 'Levels',
                  icon: Icons.grid_view_rounded,
                  onPressed: () => unawaited(_open(const LevelPicker())),
                ),
                const SizedBox(height: 22),
                // The settings, such as they are, in the place the sound switch
                // used to be. Two faders rather than one switch, because the
                // bed and the blips are not the same kind of sound and a player
                // may well want one without the other.
                _Fader(
                  label: 'Music',
                  loud: Icons.music_note_rounded,
                  quiet: Icons.music_off_rounded,
                  value: audioSettings.musicVolume,
                  onChanged: (double v) async {
                    await ambience.setMusicVolume(v);
                    if (mounted) {
                      setState(() {});
                    }
                  },
                ),
                _Fader(
                  label: 'Effects',
                  loud: Icons.volume_up_rounded,
                  quiet: Icons.volume_off_rounded,
                  value: audioSettings.effectsVolume,
                  onChanged: (double v) async {
                    await ambience.setEffectsVolume(v);
                    if (mounted) {
                      setState(() {});
                    }
                  },
                ),
                const Spacer(flex: 2),
                Text(
                  '${progress.clearedCount} of ${LevelPlan.levelCount} cleared',
                  style: const TextStyle(color: Colors.white24, fontSize: 13),
                ),
                const SizedBox(height: 18),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// A board behind the words, faded far enough back to read over.
class _Backdrop extends StatelessWidget {
  const _Backdrop({required this.level});

  final Level level;

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        final BoardCamera camera =
            BoardCamera(size: level.size, viewport: constraints.biggest)
              ..fit()
              // In a little, so the arrows run off the edges rather than
              // sitting in a square in the middle looking like a diagram.
              ..zoom = 1.35;
        return Opacity(
          opacity: 0.22,
          child: CustomPaint(
            painter: BoardPainter(
              camera: camera,
              frames: <ArrowFrame>[
                for (final Arrow arrow in level.arrows) ArrowFrame(arrow),
              ],
            ),
          ),
        );
      },
    );
  }
}

/// One volume, as a slider. Sized and coloured to sit under the buttons above
/// it rather than compete with them.
class _Fader extends StatelessWidget {
  const _Fader({
    required this.label,
    required this.loud,
    required this.quiet,
    required this.value,
    required this.onChanged,
  });

  final String label;
  final IconData loud;
  final IconData quiet;
  final double value;
  final ValueChanged<double> onChanged;

  @override
  Widget build(BuildContext context) {
    final bool off = value <= 0;
    return SizedBox(
      width: 240,
      child: Row(
        children: <Widget>[
          Icon(
            off ? quiet : loud,
            size: 18,
            color: off ? Colors.white24 : Colors.white54,
          ),
          Expanded(
            child: Slider(
              value: value,
              onChanged: onChanged,
              activeColor: off ? Colors.white24 : Colors.white70,
              inactiveColor: Colors.white12,
            ),
          ),
          SizedBox(
            width: 34,
            child: Text(
              label,
              style: const TextStyle(color: Colors.white38, fontSize: 11),
            ),
          ),
        ],
      ),
    );
  }
}
